name: javascript checks

on: [push, pull_request, workflow_dispatch, workflow_call]

permissions:
  contents: read

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v5
      - name: Pull changes
        run: git pull
        continue-on-error: true
      - uses: oven-sh/setup-bun@v2
      - name: Install modules
        run: bun install
      - name: Run ESLint
        run: bun lint
      - name: Run Svelte Check
        run: |
          bun src/lib/utils/generateDeclarations.js
          bun -b check
